// Seed data for Applyflow CRM
// Seeded from research documents: "Global Remote Design Talent Search" & "Global Talent Sweep"
// Optimised for Nigerian mid-level product designer (WAT timezone)

export const seedOpportunities = [
  {
    "id": "opp-001",
    "company_name": "Ghost",
    "role_title": "Product Designer",
    "country": "Remote Worldwide",
    "company_type": "SaaS",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Cursor, v0, LLMs for front-end coding support",
    "key_tools_mentioned": "Figma, HTML & CSS, React (Bonus)",
    "salary_estimate": "$80,000 – $110,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active Hiring",
    "wat_compatibility": "Perfect",
    "career_page": "https://careers.ghost.org",
    "application_link": "https://careers.ghost.org/product-designer-2/en/apply",
    "linkedin_page": "https://linkedin.com/company/ghost-foundation",
    "founder_hr_name": "John O'Nolan (CEO), Hannah Wolfe (CTO)",
    "outreach_method": "Direct Apply / Personal Email Pitch",
    "why_i_have_a_chance": "Ghost evaluates talent entirely through paid, collaborative trial projects (10-20 hours) rather than traditional CV/pedigree screening. Perfectly aligned with WAT timezone.",
    "portfolio_advice": "Showcase clean component systems, a strong design-to-code workflow, and documentation. Highlight your ability to write HTML/CSS code.",
    "application_emphasis": "Emphasize autonomous execution, self-driven product thinking, and highly polished visual-to-code fidelity.",
    "status": "Researching",
    "priority": "High",
    "notes": "Non-profit open-source publishing SaaS. Outstanding culture, 4-day work week, fully async operations with 1-2 weekly syncs.",
    "follow_up_date": "2026-06-03",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-002",
    "company_name": "Metalab (Zero Team)",
    "role_title": "AI Native Product Designer",
    "country": "United States / Canada",
    "company_type": "Agency",
    "company_size": "51-200",
    "remote_status": "Remote (Americas Timezones)",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Cursor, v0, Lovable, Claude, Figma AI",
    "key_tools_mentioned": "Figma, Prototyping, Front-end code",
    "salary_estimate": "$90,000 – $130,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active Intake",
    "wat_compatibility": "Medium",
    "career_page": "https://metalab.com",
    "application_link": "https://www.workingnomads.com/job/go/1618045/",
    "linkedin_page": "https://linkedin.com/company/metalab",
    "founder_hr_name": "N/A",
    "outreach_method": "LinkedIn Outreach / Direct Apply",
    "why_i_have_a_chance": "Zero is a specialized experimental team inside Metalab focused on building working interactive prototypes rather than static mockups. High-agency execution is valued over YOE.",
    "portfolio_advice": "Provide links to working web/app code prototypes built with Claude/v0. Prove that you can bypass standard static layout boundaries.",
    "application_emphasis": "Highlight prompt-engineering UI workflows, visual design mastery, and code-literacy capabilities.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Metalab is a world-class design studio (built Slack, Coinbase). The Zero team is their forward-looking AI division.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-003",
    "company_name": "Codekeeper",
    "role_title": "Digital Product Designer",
    "country": "Netherlands",
    "company_type": "SaaS",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "LLM writing assistants, automated user testing maps",
    "key_tools_mentioned": "Figma, English Copywriting, Design Systems",
    "salary_estimate": "$45,000 – $75,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active Hiring",
    "wat_compatibility": "Perfect",
    "career_page": "https://codekeeper.co",
    "application_link": "https://codekeeper.applytojob.com/apply/QjeDy1HEiW/Digital-Product-Designer",
    "linkedin_page": "https://linkedin.com/company/codekeeper",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply",
    "why_i_have_a_chance": "Specifically optimized for mid-level candidates. The team has close European ties and perfect overlapping hours with WAT (Lagos).",
    "portfolio_advice": "Present highly systematic layouts, clear information hierarchies, and custom UX copywriting samples for dense interfaces.",
    "application_emphasis": "Emphasize structure, auto-layout proficiency, component management, and strong writing skills.",
    "status": "Applying",
    "priority": "High",
    "notes": "Cloud-based SaaS for software escrow. Extremely stable business, flat product team.",
    "follow_up_date": "2026-05-30",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-004",
    "company_name": "Hospitable.com",
    "role_title": "Staff UI/UX Product Designer",
    "country": "United States (Fully Distributed)",
    "company_type": "SaaS",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI canvas wireframing, prompt workflows",
    "key_tools_mentioned": "Figma, Whimsical, Design Tokens",
    "salary_estimate": "$110,000 – $145,000",
    "date_posted": "May 19, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://hospitable.com",
    "application_link": "https://weworkremotely.com/remote-jobs/hospitable-staff-ui-ux-product-designer-usa-emea-remote",
    "linkedin_page": "https://linkedin.com/company/hospitable-com",
    "founder_hr_name": "Pierre-Camille Hamana (CEO), Matt (Design Lead)",
    "outreach_method": "Direct Apply / LinkedIn Outreach",
    "why_i_have_a_chance": "Hires international remote contractors. Focuses heavily on clean SaaS dashboard system flows and layout clarity over legacy credentials.",
    "portfolio_advice": "Walk through dense dashboard layouts, data visualization widgets, and how you manage modular tokens.",
    "application_emphasis": "Highlight user onboarding optimizations, transaction flow designs, and clear documentation.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Property management software. Great global team, hires via contractor agreements directly.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-005",
    "company_name": "Growmodo GmbH",
    "role_title": "UI/UX Designer & AI Specialist",
    "country": "Germany",
    "company_type": "Agency",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "v0, Claude, Figma AI plugins (Fully integrated AI workflow)",
    "key_tools_mentioned": "Figma, Webflow, Design Tokens",
    "salary_estimate": "$30,000 – $55,000",
    "date_posted": "May 12, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://growmodo.com/careers",
    "application_link": "https://ng.indeed.com/",
    "linkedin_page": "https://linkedin.com/company/growmodo",
    "founder_hr_name": "Andreas S. (Founder)",
    "outreach_method": "Direct Apply / LinkedIn DM",
    "why_i_have_a_chance": "Specifically targets remote design talent from Nigeria with operational hub support in Abuja. Matches CET/WAT perfectly.",
    "portfolio_advice": "Demonstrate quick iteration speeds using AI pipelines. Show detailed client UI dashboards and landing structures.",
    "application_emphasis": "Speed, visual design fidelity, Webflow/no-code integrations, and active leverage of generative UI tools.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Design-tech subscription agency. Excellent pathway for mid-level designers to manage multiple global startups.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-006",
    "company_name": "Lemon.io",
    "role_title": "Product Designer",
    "country": "Distributed",
    "company_type": "SaaS",
    "company_size": "51-200",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "LLMs, AI prototyping components",
    "key_tools_mentioned": "Figma, Design Systems, Responsive Grids",
    "salary_estimate": "$45,000 – $75,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active Intake",
    "wat_compatibility": "High",
    "career_page": "https://lemon.io/careers",
    "application_link": "https://himalayas.app/companies/lemon-io/jobs/product-designer",
    "linkedin_page": "https://linkedin.com/company/lemon-io",
    "founder_hr_name": "Aleksandr Volodarsky (CEO)",
    "outreach_method": "Direct Apply / LinkedIn Outreach",
    "why_i_have_a_chance": "Lemon.io operates a low-friction, global developer/designer marketplace with a highly developer-centric, flat structure.",
    "portfolio_advice": "Show complex dashboard layouts, grid alignments, and a clear breakdown of product user journeys.",
    "application_emphasis": "Speed, clarity of wireframing, developer collaboration tokens, and high-fidelity mockups.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Perfect contractor matchmaking pipeline. Hires quickly with simple skills testing.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-007",
    "company_name": "Visme",
    "role_title": "Senior Product Designer",
    "country": "United States",
    "company_type": "SaaS",
    "company_size": "51-200",
    "remote_status": "Fully Remote Worldwide",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Generative AI UI, agentic templates",
    "key_tools_mentioned": "Figma, AI models, complex canvas engines",
    "salary_estimate": "$70,000 – $105,000",
    "date_posted": "May 1, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://visme.co/careers",
    "application_link": "https://weworkremotely.com/remote-jobs/visme-senior-product-designer",
    "linkedin_page": "https://linkedin.com/company/visme",
    "founder_hr_name": "Payman Taei (Founder)",
    "outreach_method": "Direct Apply / LinkedIn Pitch",
    "why_i_have_a_chance": "Visme evaluates talent entirely based on actual problem solving and layout logic rather than pedigree or geography.",
    "portfolio_advice": "Show a case study where you designed a complex canvas editor, dynamic media tool, or data-heavy builder.",
    "application_emphasis": "System design, interaction heuristics, dense sidebar structures, and template logic.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Leading presentation and graphic SaaS. Distributed, async-heavy structure.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-008",
    "company_name": "AmorServ",
    "role_title": "AI-Native UI/UX Designer",
    "country": "United States",
    "company_type": "AI Startup",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Figma AI, v0, Galileo, Magic Patterns, Midjourney",
    "key_tools_mentioned": "Figma, Framer, CSS grids",
    "salary_estimate": "$50,000 – $80,000",
    "date_posted": "May 1, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://amorserv.com",
    "application_link": "https://careers-page.com/amorserv",
    "linkedin_page": "https://linkedin.com/company/amorserv",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply / LinkedIn Outreach",
    "why_i_have_a_chance": "Highly active Nigerian remote talent pipeline. Actively prioritizes mid-level designers who leverage AI daily to double output speed.",
    "portfolio_advice": "Present design variations created in minutes. Show complete Framer web builds and high-speed layout systems.",
    "application_emphasis": "Figma master, AI coding/prototyping familiarity, Framer publishing speed, and high visual taste.",
    "status": "Not Started",
    "priority": "High",
    "notes": "IT & AI Solutions startup. Fully funded enterprise AI stack provided for remote hires.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-009",
    "company_name": "Flow Ninja",
    "role_title": "Visual Designer & Webflow Expert",
    "country": "Serbia",
    "company_type": "No-Code Studio",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Figma AI, Webflow AI assets",
    "key_tools_mentioned": "Figma, Webflow, Design Systems",
    "salary_estimate": "$36,000 – $55,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active Intake",
    "wat_compatibility": "Perfect",
    "career_page": "https://flowninja.com/careers",
    "application_link": "mailto:petra@flow.ninja",
    "linkedin_page": "https://linkedin.com/company/flowninja",
    "founder_hr_name": "Stefan Mikic (CTO), Petra Nikolic (HR)",
    "outreach_method": "Direct Email Pitch (petra@flow.ninja)",
    "why_i_have_a_chance": "Flat hiring structure that actively welcomes direct cold emails and visual portfolio pitches. Fully aligned with WAT timezone.",
    "portfolio_advice": "Include links to 3 premium live Webflow sites and clean matching Figma component files with auto-layouts.",
    "application_emphasis": "High-fidelity typography, interactive animations, clean layout spacing, and quick publishing speeds.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Leading global Webflow Enterprise Agency. Friendly async culture, flat organizational chart.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-010",
    "company_name": "ClickHouse",
    "role_title": "Product Designer",
    "country": "United States",
    "company_type": "SaaS",
    "company_size": "201-500",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "LLMs, terminal layouts, analytical tools",
    "key_tools_mentioned": "Figma, design systems, SQL consoles, dark layouts",
    "salary_estimate": "$142,000 – $197,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://clickhouse.com/careers",
    "application_link": "https://dynamitejobs.com/skill/remote-ui-ux-design-jobs",
    "linkedin_page": "https://linkedin.com/company/clickhouse",
    "founder_hr_name": "Aaron Katz (CEO)",
    "outreach_method": "Direct Apply / LinkedIn Pitch",
    "why_i_have_a_chance": "ClickHouse employs a highly async-first remote structure. They value designers with strong logical/system thinking who can parse complex data panels.",
    "portfolio_advice": "Showcase code terminals, dense analytics tables, SQL editors, query grids, and highly structured dark UI modes.",
    "application_emphasis": "Data visualization, developer tool UX, system thinking, and complex information layout setups.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Real-time analytical database scaleup. Highly technical product, highly rewarding design environment.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-011",
    "company_name": "Lindy.ai",
    "role_title": "Senior Product Designer",
    "country": "United States",
    "company_type": "AI Startup",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Figma, Claude, Cursor, prompt-driven generative UI",
    "key_tools_mentioned": "Figma, HTML & CSS, LLM inputs",
    "salary_estimate": "$170,000 – $220,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Medium",
    "career_page": "https://lindy.ai/careers",
    "application_link": "https://builtin.com/jobs/remote/design-ux/search/product-designer",
    "linkedin_page": "https://linkedin.com/company/lindy-ai",
    "founder_hr_name": "Flo Crivello (Founder)",
    "outreach_method": "Twitter/X Pitch / Direct Apply",
    "why_i_have_a_chance": "They build conversational AI platforms. Prioritize quick-moving generalists who design conversational cards and fluid systems.",
    "portfolio_advice": "Highlight interactive chat spaces and dynamic cards that rearrange based on state or prompts. Include Figma system variables.",
    "application_emphasis": "Fast product execution, system thinking, conversational UI structures, and microinteractions.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Conversational AI agents platform. Very high compensation, extremely fast execution pace.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-012",
    "company_name": "Moniepoint",
    "role_title": "Senior UX/UI Designer",
    "country": "Nigeria",
    "company_type": "Fintech",
    "company_size": "201-500",
    "remote_status": "Hybrid / Remote (Lagos)",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Figma tokens, component AI plugins",
    "key_tools_mentioned": "Figma, Atomic Design, Design Tokens, Android SDK",
    "salary_estimate": "$24,000 – $45,000",
    "date_posted": "May 9, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://moniepoint.com/careers",
    "application_link": "https://ng.indeed.com/",
    "linkedin_page": "https://linkedin.com/company/moniepoint",
    "founder_hr_name": "Felix Ike (Co-founder & CTO)",
    "outreach_method": "Direct Apply / LinkedIn Outreach",
    "why_i_have_a_chance": "Africa's 2nd fastest-growing tech platform. Lagos hub is local but operates at a global scale. Ideal for structured local designers with world-class taste.",
    "portfolio_advice": "Showcase a massive design system library you built or maintained. Walk through merchant transaction checkout states in mobile format.",
    "application_emphasis": "Atomic component structures, auto-layout variables, dark/light compliance, and local payment flow UX.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Premier digital business banking scaleup in Nigeria. Highly competitive compensation for local market.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-013",
    "company_name": "VPD Money",
    "role_title": "UI/UX Developer",
    "country": "Nigeria",
    "company_type": "Fintech",
    "company_size": "11-50",
    "remote_status": "Fully Remote (Lagos Hub)",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI layout suggestions, code helpers",
    "key_tools_mentioned": "Figma, CSS, HTML5, Mobile-first responsive grids",
    "salary_estimate": "₦4.8M – ₦9.6M / yr",
    "date_posted": "May 19, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://vpd.money",
    "application_link": "https://ng.indeed.com/",
    "linkedin_page": "https://linkedin.com/company/vpd-money",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply / LinkedIn Outreach",
    "why_i_have_a_chance": "Lagos-operated cross-border digital banking platform. Hires mid-level design-engineers who can bridge layout design with high-quality CSS.",
    "portfolio_advice": "Show a side-by-side comparison of a Figma layout screen and the corresponding live responsive HTML/CSS page.",
    "application_emphasis": "Cross-border wallet transactions, visual transaction state alerts, and clean HTML/CSS conversion.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Digital banking platform for diaspora payments. Flat organization, fast hiring cycles.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-014",
    "company_name": "Brew Crypto LLC",
    "role_title": "UI/UX Designer",
    "country": "Nigeria",
    "company_type": "Fintech",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Cursor, Figma code generation",
    "key_tools_mentioned": "Figma, CSS grids, Shadcn/ui component tokens",
    "salary_estimate": "$24,000 – $42,000",
    "date_posted": "May 20, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://brewcrypto.com",
    "application_link": "https://ng.indeed.com/",
    "linkedin_page": "https://linkedin.com/company/brewcrypto",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply",
    "why_i_have_a_chance": "Lagos-based Web3 & crypto SaaS team. Hires designers who work closely with engineers using Tailwind and Shadcn CSS frameworks.",
    "portfolio_advice": "Highlight dark-mode crypto dashboards, modular token cards, yield tracking charts, and clear transactional states.",
    "application_emphasis": "Web3 wallet connection flows, transaction ledger tables, dark UI aesthetics, and developer handoff guidelines.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Fast-moving crypto platform. Hires via direct contract paid in USD/Stablecoin.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-015",
    "company_name": "SaaS Web Apps",
    "role_title": "AI-Savvy Product/UX Generalist",
    "country": "Global / Remote",
    "company_type": "Reddit",
    "company_size": "1-10",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Figma AI, AI text tools, v0 builds",
    "key_tools_mentioned": "Figma, User Psychology, Layout Audit",
    "salary_estimate": "$40,000 – $60,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "N/A",
    "application_link": "https://www.reddit.com/r/forhire/comments/1tieo5l/hiring_looking_for_an_aisavvy_productux_generalist/",
    "linkedin_page": "N/A",
    "founder_hr_name": "SaaS Founder",
    "outreach_method": "Reddit Direct Message (DM)",
    "why_i_have_a_chance": "Direct Reddit hire bypasses all ATS filters. You engage directly with the founder who values practical usability audits and fast product revisions.",
    "portfolio_advice": "Show a before-and-after audit where you completely redesigned a messy SaaS screen to improve registration or checkout conversions.",
    "application_emphasis": "Heuristics audit, registration flow simplifications, rapid layouts, and direct conversion thinking.",
    "status": "Researching",
    "priority": "High",
    "notes": "Bootstrapped SaaS founder hiring a generalist to clean up their product UX prior to a major relaunch.",
    "follow_up_date": "2026-05-29",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-016",
    "company_name": "RevenueCat",
    "role_title": "Senior Product Designer",
    "country": "United States",
    "company_type": "SaaS",
    "company_size": "51-200",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes (Hires in EMEA)",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "LLMs, automated documentation",
    "key_tools_mentioned": "Figma, design system variables, transactional charts",
    "salary_estimate": "$110,000 – $145,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://revenuecat.com/careers",
    "application_link": "https://4dayweek.io/remote-design-jobs",
    "linkedin_page": "https://linkedin.com/company/revenuecat",
    "founder_hr_name": "Jacob Eiting (CEO)",
    "outreach_method": "LinkedIn DM / Direct Apply",
    "why_i_have_a_chance": "Explicitly hires remote design contractors in EMEA/African timezone offsets. Highly async and documents everything.",
    "portfolio_advice": "Highlight chart systems, in-app billing widgets, visual pricing paywalls, and dense transaction log grids.",
    "application_emphasis": "Data visualization, paywall interaction flows, billing system tables, and Figma variables mastery.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Subscription infrastructure SaaS. 4-day work week, outstanding compensation, extremely developer-friendly.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-017",
    "company_name": "Cosuno",
    "role_title": "Sr. Product Designer",
    "country": "Germany",
    "company_type": "SaaS",
    "company_size": "51-200",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "v0, layout helpers",
    "key_tools_mentioned": "Figma, design system tokens, complex form grids",
    "salary_estimate": "$70,000 – $95,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://cosuno.de/careers",
    "application_link": "https://dynamitejobs.com/skill/remote-ui-ux-design-jobs",
    "linkedin_page": "https://linkedin.com/company/cosuno",
    "founder_hr_name": "Christoph J. (Founder)",
    "outreach_method": "Direct Apply",
    "why_i_have_a_chance": "Based in Germany, fully aligned with WAT (Lagos Time). High-growth SaaS hiring remote experts for data-dense B2B grids.",
    "portfolio_advice": "Showcase high-density tables with multi-select items, inline edit cell fields, modal popups, and audit history widgets.",
    "application_emphasis": "B2B complex workflows, data tables, modular form systems, and design tokens.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Construction procurement SaaS. Perfect timezone overlap, stable company.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-018",
    "company_name": "Teramind",
    "role_title": "Lead UX Designer",
    "country": "Global",
    "company_type": "SaaS",
    "company_size": "51-200",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI analytics panels",
    "key_tools_mentioned": "Figma, security dashboards, tracking grids, graphs",
    "salary_estimate": "$60,000 – $120,000",
    "date_posted": "May 19, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://teramind.co/careers",
    "application_link": "https://dynamitejobs.com/skill/remote-ui-ux-design-jobs",
    "linkedin_page": "https://linkedin.com/company/teramind",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply",
    "why_i_have_a_chance": "Provides fully borders-free global hiring with highly async channels. The product requires heavy design system controls and dense metrics dashboards.",
    "portfolio_advice": "Present complex tracking graphs, timeline grids, filter dropdowns, and data security panels.",
    "application_emphasis": "Data visualization, advanced charting components, filter hierarchy, and sidebar layouts.",
    "status": "Not Started",
    "priority": "Low",
    "notes": "User activity monitoring and insider threat prevention SaaS. Highly async.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-019",
    "company_name": "Mercury",
    "role_title": "Senior Product Designer",
    "country": "United States",
    "company_type": "Fintech",
    "company_size": "201-500",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI data summaries, layout assistants",
    "key_tools_mentioned": "Figma, banking tokens, bookkeeping tables",
    "salary_estimate": "$189,000 – $236,000",
    "date_posted": "May 23, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://mercury.com/jobs",
    "application_link": "https://4dayweek.io/remote-design-jobs",
    "linkedin_page": "https://linkedin.com/company/mercury-banking",
    "founder_hr_name": "Immad Akhund (CEO)",
    "outreach_method": "Direct Apply / LinkedIn Pitch",
    "why_i_have_a_chance": "Standard-setting banking platform that hires globally via local contractor entities. Prioritizes pristine design system precision and pixel alignments.",
    "portfolio_advice": "Show complex ledger tables, currency cards, multi-actor settings lists, and pristine clean typography systems.",
    "application_emphasis": "Absolute visual design polish, pixel-perfect layouts, clear information density, and interactive payment forms.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Outstanding financial platform for startups. Hires remote workers and pays extremely high competitive compensation.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-020",
    "company_name": "Flow Unbounded",
    "role_title": "Webflow Growth Designer",
    "country": "United States",
    "company_type": "No-Code Studio",
    "company_size": "1-10",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Figma AI, Relume builder",
    "key_tools_mentioned": "Figma, Webflow, Client Onboarding layouts",
    "salary_estimate": "$40,000 – $65,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://flownbound.com",
    "application_link": "https://www.flowroles.com/webflow-agencies",
    "linkedin_page": "https://linkedin.com/company/flowunbounded",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply / LinkedIn Outreach",
    "why_i_have_a_chance": "Small agile team launching startups' landing pages in Webflow. Values visual polish, responsive typography, and fast turnaround.",
    "portfolio_advice": "Highlight premium visual interactions, custom grid structures, Webflow code integrations, and landing conversions.",
    "application_emphasis": "High visual polish, typography contrast, interaction transitions, and fast execution speeds.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Fast-growing Webflow agency. Simple hiring process without massive corporate red tape.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-021",
    "company_name": "InEvent",
    "role_title": "UI / UX Designer",
    "country": "United States (Active in Nigeria)",
    "company_type": "SaaS",
    "company_size": "51-200",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI layout suggestions, automated asset generation",
    "key_tools_mentioned": "Figma, Photoshop, Illustrator, HTML, CSS, WordPress",
    "salary_estimate": "$50,000 – $80,000",
    "date_posted": "May 23, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://inevent.com/en/careers.php",
    "application_link": "https://himalayas.app",
    "linkedin_page": "https://linkedin.com/company/inevent",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply / LinkedIn",
    "why_i_have_a_chance": "Excellent flat structure for mid-level designers. Fully remote with asynchronous communication across 13+ countries. Strong history of hiring remote talent in WAT/Nigeria.",
    "portfolio_advice": "Present navigation-friendly wireframes, custom CSS pages, responsive web layouts, and marketing digital assets.",
    "application_emphasis": "B2B SaaS design, multi-platform design experience, and clean wireframe execution.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Event Tech SaaS startup with direct involvement in B2B platform design cycles.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-022",
    "company_name": "Blossom",
    "role_title": "Middle Product Designer",
    "country": "United States (Global Remote)",
    "company_type": "Fintech",
    "company_size": "11-50",
    "remote_status": "100% Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI Tools, generative layout assistants",
    "key_tools_mentioned": "Figma, AI Tools, HTML/CSS",
    "salary_estimate": "$60,000 – $90,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://blossom.inc",
    "application_link": "https://www.workingnomads.com/jobs/middle-product-designer-blossom",
    "linkedin_page": "N/A",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply",
    "why_i_have_a_chance": "Explicitly values a strong portfolio from a 2-year designer over a legacy 10-year brief-executer. Prioritizes designers who leverage daily AI tools.",
    "portfolio_advice": "Show portfolio project with clear HTML/CSS understanding. Demonstrate AI tool usage for accelerating design output.",
    "application_emphasis": "End-to-end design problem ownership, translating undefined briefs into clear user flows, and HTML/CSS component literacy.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Fintech platform for credit unions. Fully remote, multicultural workspace requiring fluent English.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-023",
    "company_name": "Circle (circle.so)",
    "role_title": "Lead Product Designer, Marketplace",
    "country": "United States (Fully Remote Global)",
    "company_type": "AI Startup",
    "company_size": "51-200",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Cursor, Claude Code, Figma, Lovable, v0",
    "key_tools_mentioned": "Figma, AI prototyping, marketplace design patterns",
    "salary_estimate": "$120,000 – $170,000",
    "date_posted": "May 23, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://circle.so/careers",
    "application_link": "https://flexa.careers",
    "linkedin_page": "https://linkedin.com/company/circle-so",
    "founder_hr_name": "Sid Yadav (CEO)",
    "outreach_method": "Direct Apply / Founder Outreach",
    "why_i_have_a_chance": "Highly decentralized community SaaS, async-first. Twice-yearly team offsites, highly documented asynchronous workspace. Competitive compensation.",
    "portfolio_advice": "Reference marketplace design patterns. Show complex trust mechanics and AI-driven interaction models.",
    "application_emphasis": "AI-native pitch, marketplace discovery engine design, and async-first culture fit.",
    "status": "Not Started",
    "priority": "High",
    "notes": "AI-driven SaaS communities platform. Own the marketplace discovery engine end-to-end.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-024",
    "company_name": "Wealth.com",
    "role_title": "Senior UX Product Designer",
    "country": "United States",
    "company_type": "Fintech",
    "company_size": "51-200",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI prototyping tools, generative layout experiments",
    "key_tools_mentioned": "Figma, Microinteractions, Design Tokens",
    "salary_estimate": "$100,000 – $140,000",
    "date_posted": "May 22, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://wealth.com",
    "application_link": "https://weworkremotely.com/remote-jobs/wealth-com-senior-ux-product-designer",
    "linkedin_page": "https://linkedin.com/company/wealth-com",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply",
    "why_i_have_a_chance": "Modern legal tech platform that values AI prototyping actively. Distributed model with flexible PTO and supportive recharge cultures.",
    "portfolio_advice": "Focus on microinteractions, design tokens, and AI-assisted prototyping work.",
    "application_emphasis": "Evolving design systems to support scalability, using tokens, introducing delight through microinteractions.",
    "status": "Not Started",
    "priority": "High",
    "notes": "Fintech / Legal Tech platform. Values candidates who actively use AI tools to accelerate prototyping.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-025",
    "company_name": "Archlet",
    "role_title": "Senior Product Designer",
    "country": "Switzerland",
    "company_type": "SaaS",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI-assisted user research, automated flow mapping",
    "key_tools_mentioned": "Figma, User Research, Complex Data Dashboards",
    "salary_estimate": "$80,000 – $120,000",
    "date_posted": "May 7, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://archlet.io/careers",
    "application_link": "https://weworkremotely.com/remote-jobs/archlet-senior-product-designer",
    "linkedin_page": "https://linkedin.com/company/archlet",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply",
    "why_i_have_a_chance": "SaaS platform focusing on complex B2B layout design. Swiss company with high European timezone overlap, fully compatible with WAT.",
    "portfolio_advice": "Translate complex data requirements into intuitive layouts, user journeys, and dashboard interactions.",
    "application_emphasis": "Complex B2B workflow navigation, structured logical design rather than purely visual artistry.",
    "status": "Not Started",
    "priority": "High",
    "notes": "B2B Procurement SaaS. Position as a designer who simplifies complex data flows.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-026",
    "company_name": "Karpi Studio",
    "role_title": "Webflow UX/UI Designer",
    "country": "United States",
    "company_type": "No-Code Studio",
    "company_size": "1-10",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Figma AI, layout automation",
    "key_tools_mentioned": "Webflow, Figma, Design Systems",
    "salary_estimate": "$35,000 – $55,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://karpistudio.com",
    "application_link": "https://flowroles.com",
    "linkedin_page": "https://linkedin.com/company/karpi-studio",
    "founder_hr_name": "N/A",
    "outreach_method": "LinkedIn / Direct Apply",
    "why_i_have_a_chance": "Boutique studio working closely with high-growth startups, prioritizing fast visual design execution.",
    "portfolio_advice": "Lead with landing page conversions and startup work. Show high-performing, clean websites.",
    "application_emphasis": "Modern design fidelity, clean layout structures, and conversion-driven landing pages.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Boutique Webflow studio focused on fast visual design for startups.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-027",
    "company_name": "Grafit Agency",
    "role_title": "Webflow Designer & Developer",
    "country": "Poland",
    "company_type": "No-Code Studio",
    "company_size": "1-10",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "Animation libraries, generative assets",
    "key_tools_mentioned": "Webflow, Figma, Animation Libraries",
    "salary_estimate": "$30,000 – $50,000",
    "date_posted": "May 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://grafitagency.com",
    "application_link": "https://flowroles.com",
    "linkedin_page": "https://linkedin.com/company/grafitagency",
    "founder_hr_name": "N/A",
    "outreach_method": "Email / LinkedIn",
    "why_i_have_a_chance": "High Western European timezone overlap, fully compatible with WAT. Flat agency model providing opportunity to manage full client lifecycles.",
    "portfolio_advice": "Show Webflow/Figma combo. Mention WAT overlap with CET timezone.",
    "application_emphasis": "Responsive, fast, scalable Webflow sites with clean layouts and custom interactions.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "No-code Webflow agency based in Poland. Flat hiring structure.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-028",
    "company_name": "Circle (circle.com)",
    "role_title": "Lead Product Designer (Identity)",
    "country": "United States",
    "company_type": "Fintech",
    "company_size": "201-500",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI-assisted authentication flows",
    "key_tools_mentioned": "Figma, Auto-layout, Variables, Variants",
    "salary_estimate": "$130,000 – $180,000",
    "date_posted": "May 23, 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "https://circle.com/en/careers",
    "application_link": "https://careers.circle.com",
    "linkedin_page": "https://linkedin.com/company/circleinternetfinancial",
    "founder_hr_name": "Jeremy Allaire (CEO)",
    "outreach_method": "Direct Apply / LinkedIn",
    "why_i_have_a_chance": "Globally scaling across major international jurisdictions. Ideal for system-driven designers who excel at component-based logic inside Figma.",
    "portfolio_advice": "Figma systems depth: auto-layout, variables, variants for Web3 auth flows.",
    "application_emphasis": "Audit fragmented client workflows and unify into structural authentication, permissions, and billing frameworks.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Web3 fintech platform. Emphasize token/variables Figma expertise and complex system design.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-029",
    "company_name": "InvisionHub",
    "role_title": "Lead Product Designer",
    "country": "Nigeria (Lagos Hub)",
    "company_type": "Agency",
    "company_size": "11-50",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI prototyping, component generation",
    "key_tools_mentioned": "Figma, Design Systems, Prototyping",
    "salary_estimate": "₦6M – ₦12M / yr",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://invisionhub.com",
    "application_link": "https://bebee.com/ng/jobs/role/ui-designer",
    "linkedin_page": "N/A",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply / Email Pitch",
    "why_i_have_a_chance": "Perfectly aligned with WAT. Lagos-based creative studio with local remote options. Focuses on building digital products for startups and local enterprises.",
    "portfolio_advice": "Emphasize local startup ecosystem knowledge. Show component libraries and full design lifecycle work.",
    "application_emphasis": "Visual design, component library maintenance, translating business logic into layouts.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Creative-Tech Agency / Startup Studio based in Lagos. Hybrid and remote setups common.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-030",
    "company_name": "Figma",
    "role_title": "Product Designer – AI Models",
    "country": "United States",
    "company_type": "SaaS",
    "company_size": "1000+",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI models, design heuristics, LLM copilots",
    "key_tools_mentioned": "Figma, AI Models, Design Heuristics",
    "salary_estimate": "$150,000 – $220,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Medium",
    "career_page": "https://figma.com/careers",
    "application_link": "https://www.workingnomads.com/jobs/product-designer-ai-models-figma-1624679",
    "linkedin_page": "https://linkedin.com/company/figma",
    "founder_hr_name": "Dylan Field (CEO)",
    "outreach_method": "Direct Apply / LinkedIn",
    "why_i_have_a_chance": "Perfect for systematic, product-minded designers interested in training LLMs and design copilots. Works across complex cross-functional boundaries.",
    "portfolio_advice": "AI design heuristics angle. Show systematic design thinking depth.",
    "application_emphasis": "Partnering with AI researchers to improve model design heuristics, testing and enhancing AI-generated output quality.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "Design Tools company. High compensation, works across complex organizational boundaries.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-031",
    "company_name": "DotYeti Design",
    "role_title": "Senior Motion Graphic Designer",
    "country": "Global (Lagos Operations)",
    "company_type": "Agency",
    "company_size": "51-200",
    "remote_status": "Remote / Hybrid",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI asset generation, automated compositions",
    "key_tools_mentioned": "After Effects, Premiere, Figma",
    "salary_estimate": "$30,000 – $55,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "Perfect",
    "career_page": "https://dotyeti.com/careers",
    "application_link": "https://ng.indeed.com/",
    "linkedin_page": "https://linkedin.com/company/dotyeti",
    "founder_hr_name": "N/A",
    "outreach_method": "Direct Apply / LinkedIn",
    "why_i_have_a_chance": "Explicitly requests mid-shift hours (3:00 PM – 11:00 PM WAT) to support their global remote team. Strong WAT operational alignment.",
    "portfolio_advice": "Prepare motion/UI hybrid portfolio examples. Show motion-centric visual storytelling assets.",
    "application_emphasis": "Motion design, visual storytelling, layout and flow optimization, and UX/UI mindset.",
    "status": "Not Started",
    "priority": "Low",
    "notes": "Creative Design Agency with specific WAT shift coverage. Content and motion focus.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-032",
    "company_name": "Clay",
    "role_title": "Product Designer (General Intake)",
    "country": "United States",
    "company_type": "Agency",
    "company_size": "51-200",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI prototyping, generative design tools",
    "key_tools_mentioned": "Figma, Prototyping Tools, Design Systems",
    "salary_estimate": "$70,000 – $110,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active Intake",
    "wat_compatibility": "High",
    "career_page": "https://clay.global/careers",
    "application_link": "https://clay.global",
    "linkedin_page": "https://linkedin.com/company/clayglobal",
    "founder_hr_name": "N/A",
    "outreach_method": "LinkedIn Outreach / Direct Apply",
    "why_i_have_a_chance": "Specializes in launching sleek products for fast-growing startups and digital dashboards. High emphasis on polished visual assets and design system logic.",
    "portfolio_advice": "Present cleanest portfolio pieces. Show high-end SaaS dashboards and modern consumer interfaces.",
    "application_emphasis": "Intuitive layouts, responsive design frameworks, user research for modern SaaS environments.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "High-end UI/UX design agency focused on modern SaaS dashboards and consumer products.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "id": "opp-033",
    "company_name": "Valorsicstudio",
    "role_title": "Remote Website Designer",
    "country": "Global / Remote",
    "company_type": "Agency",
    "company_size": "1-10",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes",
    "mid_entry_friendly": "Yes",
    "ai_workflow_mentioned": "AI layout tools",
    "key_tools_mentioned": "Figma, Clean Minimal Web Layout",
    "salary_estimate": "$25,000 – $45,000",
    "date_posted": "Q2 2026",
    "hiring_freshness": "Active",
    "wat_compatibility": "High",
    "career_page": "N/A",
    "application_link": "https://www.reddit.com/r/DesignJobs/comments/1s4eind/hiring_remote_website_designer_upcoming_q2_2026/",
    "linkedin_page": "N/A",
    "founder_hr_name": "Valorsicstudio Founder",
    "outreach_method": "Reddit Direct Message (DM)",
    "why_i_have_a_chance": "Project-based, long-term collaboration model designed for visual product designers. Async-friendly with flexible timeline execution.",
    "portfolio_advice": "Show clean layout work and hierarchy mastery. Present minimal, high-trust designs.",
    "application_emphasis": "Minimal design angle, layout hierarchy understanding, and user flow for consulting brands.",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "B2B Digital Studio. Found via Reddit. Short pitch with portfolio link is the ideal approach.",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": ""
  },
  {
    "company_name": "WEX",
    "role_title": "UX Product Designer / Hybrid Design Engineer",
    "country": "Global",
    "company_type": "B2B Payment Systems",
    "company_size": "1000+",
    "remote_status": "Fully Remote",
    "global_remote_friendly": "Yes (Distributed global team)",
    "mid_entry_friendly": "Mid-level friendly",
    "wat_compatibility": "High (Self-directed schedule alignment)",
    "salary_estimate": "$85,000 – $120,000 USD/year",
    "date_posted": "May 19, 2026",
    "hiring_freshness": "Active",
    "career_page": "https://wexinc.com/careers",
    "application_link": "",
    "linkedin_page": "https://linkedin.com/company/wex-inc",
    "founder_hr_name": "",
    "outreach_method": "",
    "key_tools_mentioned": "",
    "ai_workflow_mentioned": "",
    "why_i_have_a_chance": "",
    "portfolio_advice": "",
    "application_emphasis": "",
    "status": "Not Started",
    "priority": "Medium",
    "notes": "",
    "follow_up_date": "",
    "applied_date": "",
    "interview_stage": "",
    "id": "opp-034"
  }
];
